baseURL: "https://jinalpawar.github.io/"
languageCode: "en-us"
title: "Jinal's Portfolio"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  # main:
    # - identifier: blog
    #   name: Blog
    #   title: Blog posts
    #   url: /blogs
    #   weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Jinal Pawar"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: /lasun_favicon.webp

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
    textColor: 
    secondaryTextColor: "#A30262"
    backgroundColor: "#fffaf8"
    secondaryBackgroundColor: "#fffcfb" 
    primaryColor: "#B55690"
    secondaryColor: 

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Jinal Pawar" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Jinal."
    subtitle: "I mess around with Data."
    content: |
          A Data Scientist, Machine Learning Enthusiast and Feline specialist 
          (That's my cat, Lasun).
          
          I am dedicated to working on interdisciplinary projects and use ML & DS to do cool stuff.
    image: /lasun_1.webp
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/jinal_pawar_resume.pdf"
      download: true
      newPage: false
    # socialLinks:
    #   fontAwesomeIcons:
    #     - icon: fab fa-github
    #       url: https://example.com
    #     - icon: fab fa-x-twitter
    #       url: https://example.com
    #   customIcons:
    #     - icon: /fav.png
    #       url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: /jinal.webp
    content: |-
      I am a Data Scientist with a strong interest in interdisciplinary research in Human Cognition and Machine Learning. I have experience in ML, DS and Software Development as well.
    skills:
      enable: true
      title: "Here are a few technologies I've worked with:"
      items:
        - "Python"
        - "OpenCV"
        - "Sci-kit Learn"
        - "Pandas"
        - "Django"
        - "Power BI"
        - "Tableau"
        - "MySQL"
        - "PostgreSQL"
        - "Numpy"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Software Developer/Data Analyst"
        company: "Bashir International"
        # companyUrl: "https://example.com"
        date: "Feb 2023 - Nov 2023"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: |- 
            I developed Soko - an Inventory Management System with built-in Data Analytics Dashboard. I used Django & DRF for backend, PostgreSQL for database and Metabase for the Dashboard. 
            
            I developed  Create Sales, Add & List orders, Automatic Bill PDF Creation, Return Items, Update Stock, Store Customer Details, and more such features.
        
        
            Through the Sales dashboard, I developed showcased revenue trends by categories and subcategories as well as customer purchase patterns.


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Electronics Engineering"
        school:
          name: "Vidyalankar Institute of Technology"
          url: "https://vit.edu.in/"
        date: "2018 - 2022"
        GPA: "9.04 out of 10.0"
        content: |-
          Extracurricular Activities
            - Core Member of Literary Council
                - Researched, Planned and Executed a number of events such as inter-college debates, Writers' meet & greet, etc from scratch
            - Freelance Video Editor
                - Worked on Youtube videos, Promotional videos, Wedding Film
        # featuredLink:
        #   enable: true
        #   name: "My Portfolio"
        #   url: "https://www.behance.net/gallery/143730229/Video-Editing-Portfolio"
      - title: "High School"
        school:
          name: "St. Rocks Junior College"
        date: "2016 - 2018"
        GPA: "87%"
        # featuredLink:
        #   enable: true
        #   url: "https://example.com"

  # Achievements
  # achievements:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - title: Google kickstart runner
  #       content: I solved all problems with optimal solution.
  #       url: https://example.com
  #       image: /images/achievment.jpg


  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Connect
        content: Connect is an app that captures live video of a person speaking in Sign Language, recognizes the signs and transcribes them to text and audio
        image: /connect.webp
        badges:
          - "Python"
          - "Mediapipe"
          - "OpenCV"
          - "Sci-kit learn"
        featured:
          name: Paper
          link: "/connect_technical_paper.pdf"      


      - title: Bora Track
        content: Bora Track is a song recommendation system which recommends a song from an artist based on user’s selected 5 songs.
        image: /bora_tracks.webp
        badges:
          - "Python"
          - "Sci-kit learn"
        featured:
          name: Coming soon
        links:
        - icon: fab fa-github
          url:  


      - title: Soko
        content: An Inventory Management System with built-in Data Analytics Dashboard.
        image: /dashboard.webp
        featured:
          name: Demo
          link: "/soko.pdf"
        badges:
          - "Django"
          - "DRF"
          - "MetaBase"

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a collaboration proposal or just want to say hi, I'd love to talk.
    email: jinalpawar818@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    # recentPosts:
    #   path: "blogs"
    #   count: 3
    #   title: Recent Posts
    #   enable: true
    #   disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/jinalpawar
      linkedin: https://www.linkedin.com/in/jinal-pawar/
      # twitter: https://twitter.com
      # instagram: https://instagram.com
      # facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
